name: Prepare for development

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
          architecture: x64
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "gjong@users.noreply.github.com"
          git pull
      - name: Prepare next build phase
        run: |
          mvn versions:set versions:commit -DnextSnapshot -q
          NEXT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Pushing committed snapshot
        run: |
          git add .
          git commit -m "chore: prepare snapshot version ${{ env.NEXT_VERSION }}"
          git push
