name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release/release-version.yml
  github-release:
    needs: release
    runs_on: ubuntu-latest
    if: ${{ needs.release.outputs.version }}
    steps:
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          name: Release ${{ needs.release.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  prepare-next:
    needs: release
    uses: ./.github/workflows/release/prepare-snapshot.yml
